server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

indexing-settings:
  sites:
    - url: "http://www.example.com"
      name: "Example"
    - url: "http://www.example2.com"
      name: "Example2"

// indexing-settings:
//  sites:
//    - url: "http://www.example.com"
//      name: "Example"
//    - url: "http://www.example2.com"
//      name: "Example2"